FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt requirements.txt
RUN python -m pip install --upgrade pip &&\
    python -m pip install -r requirements.txt

EXPOSE 5000

COPY app.py app.py
COPY aquarium.py aquarium.py
COPY log_in.py log_in.py
COPY config.json config.json

ENTRYPOINT [ "flask", "run" ]